package model.enums;

public enum SpecialSkillType {
    ECONOMICAL_CONSTRUCTION, //OSZCZEDNA_KONSTRUKCJA
    CRAFT, //RZEMIOSLO
    NEW_IDEA, //NOWY_POMYSŁ
    HANDYMAN, //ZLOTA_RACZKA
    GRANDMAS_RECIPE, //BABCINA_RECEPTURA
    SHARP_EYE, //BYSTRE_OKO
    NAIL_SOUP, //ZUPA_Z_GWOŹDZIA
    HOOCH, //SAMOGON
    LUCKY_MAN, //DZIECKO_SZCZESCIA
    RECONNAISSANCE, //REKONESANS
    MOTIVATIONAL_SPEECH, //MOWA_KU_POKRZEPIENIU_SERC
    SCOUT, //ZWIAD
    TRACKING, //TROPIENIE
    HOUNTING, //POLOWANIE
    FURY, //FURIA
    EMERGENCY_PLAN, //PLAN_ZAPASOWY
}
