package model.enums.elements;

public enum MarkerType {
    CARPENTER_MARKER,
    COOK_MARKER,
    EXPLORER_MARKER,
    SOLDIER_MARKER,
    FRIDAY_MARKER,
    DOG_MARKER,
    HUNTING_HELPER_MARKER,
    BUILDING_HELPER_MARKER,
    GATHERING_RESOURCES_HELPER_MARKER,
    EXPLORATION_HELPER_MARKER,
    ROUND_MARKER,
    WOUND_MARKER,
    BLACK_MARKER,
    WHITE_MARKER,
    BLUE_MARKER,
    WOOD_MARKER,
    FOOD_MARKER,
    LONG_EXPIRY_DATE_FOOD_MARKER,
    HIDE_MARKER
}
