package model.enums.elements;

public enum TokenType {
    FIRST_PLAYER_TOKEN,
    BUILDING_ADVENTURE_TOKEN,
    GATHERING_RESOURCES_ADVENTURE_TOKEN,
    EXPLORATION_ADVENTURE_TOKEN,
    DISCOVERY_TOKEN,
    RAIN_CLOUD_TOKEN,
    SNOW_CLOUD_TOKEN,
    CAMP_TOKEN,
    SHELTER_TOKEN,
    DETERMINATION_TOKEN,
    SHORTCUT_TOKEN,
    STORM_TOKEN,
    BASKET_TOKEN,
    SACK_TOKEN,
    BROWN_WOUND_TOKEN,
    GRAY_WOUND_TOKEN,
    GREEN_WOUND_TOKEN,
    WOOD_PLUS_ONE_TOKEN,
    FOOD_PLUS_ONE_TOKEN,
    NEED_ONE_MORE_CHARACTER_MARKER_TOKEN,
    ROLL_AGAIN_IF_SUCCESS_TOKEN,
    BEAST_STRENGHT_PLUS_ONE_TOKEN
}
