package model.enums.cards;

public enum BuildingAdventureType {
    TOOL_BREAKS,
    LABORIOUS_WORK, //x2
    CONSTRUCTION,
    UNMOTIVATED,
    FAST_WORK,
    STING,
    NASTY_WOUND,
    TIRED,
    IN_A_HURRY,
    DARK_CLOUDS_IN_THE_SKY,
    CONSTRUCTION_IS_WEAK,
    PREDATOR_IN_THE_CAMP,
    WIND_STORM,
    FEAR_OF_THE_BEASTS,
    BREAKDOWN,
    BROKEN_LEVER,
    DANGEROUS_WORK,
    LACK_OF_HOPE,
    HARD_WORK,
    COMING_TO_TERMS,
    CUT_HEAD,
    TOOLS_INSPECTION,
    MONKEYS_WATCH_YOU,
    SAVINGS,
    ACCIDENT,
    HOWLING_IN_THE_BUSHES,
    HUNGRY_PREDATOR,
    YOU_NEED_A_BIGGER_CAMP,
    VISIT_OF_A_PREDATOR
}
