package model.enums.cards;

public enum GatheringResourcesAdventureType {
    END_OF_SOURCE, //x5
    WINTER_FREEZING,
    UNEXPECTED_DISCOVERY,
    FURS,
    SPIDER,
    SKELETON,
    SIGNS_OF_A_PREDATOR,
    PIRATES_CHEST,
    VIPER,
    UNBELIEVABLE_EFFORT,
    TWISTED_ANKLE,
    WINTER_IS_COMING,
    WEATHER_BREAKDOWN,
    UNEXPECTED_TROUBLES,
    TRACKS_OF_A_PREDATOR,
    SHORTAGE,
    MUSHROOMS,
    GOLD_COIN,
    FRUIT,
    EYES_IN_THE_BUSHES,
    AFTER_THE_HURRICANE,
    PATH_OF_A_PREDATOR,
    NICE_SURPRISE,
    NESTLINGS,
    NEW_FLOCK,
    SURPRISE_IN_THE_BUSHES
}
